name: sensordata

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "src/docker-compose.yml" up -d --build
