name: sensordata

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Start containers
        run: docker-compose -f "sensordata/docker-compose.yml" up --build --remove-orphan